//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductReceiptDetails = new HashSet<ProductReceiptDetail>();
            this.Promotions = new HashSet<Promotion>();
            this.Colors = new HashSet<Color>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ProductID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        [MaxLength(50, ErrorMessage = "Không nhập quá 50 kí tự")]
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Please enter valid Number")]
        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mã sản phẩm")]
        public string ProductCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public string Height { get; set; }
        public Nullable<int> CategoryTypeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string Material { get; set; }
        public byte[] ProductImage { get; set; }
        [Required]
        public byte[] ImageUpload { get; set; }

        public String Image { get; set; }

        public virtual CategoryType CategoryType { get; set; }
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceiptDetail> ProductReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Color> Colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
