//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.Orders = new HashSet<Order>();
            this.ProductReceiptDetails = new HashSet<ProductReceiptDetail>();
        }
    
        public int ReceiptID { get; set; }
        public string ReceiptName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> GuestID { get; set; }
        public string EndDate { get; set; }
        public string Status { get; set; }
        public string Debt { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceiptDetail> ProductReceiptDetails { get; set; }
    }
}
